const people = {
  results: [
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Cristiano', last: 'Ap Lázaro' },
      age: 43,
      location: {
        street: { number: 637, name: 'Rua João Gabriel' },
        city: 'Ribeirão Claro',
        state: 'Paraná',
        country: 'Brasil',
        postcode: 86410,
      },
      login: {
        userid: '1',
        username: 'crist1',
        password: 'sdfsd',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Elenice', last: 'C Lázaro' },
      age: 41,
      location: {
        street: { number: 637, name: 'Rua João Gabriel' },
        city: 'Ribeirão Claro',
        state: 'Paraná',
        country: 'Brasil',
        postcode: 86410,
      },
      login: {
        userid: '2',
        username: 'elen1',
        password: 'dfdfdf',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Cristiane', last: 'C Lázaro' },
      age: 15,
      location: {
        street: { number: 637, name: 'Rua João Gabriel' },
        city: 'Ribeirão Claro',
        state: 'Paraná',
        country: 'Brasil',
        postcode: 86410,
      },
      login: {
        userid: '3',
        username: 'crist2',
        password: 'lkjdsf',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Bruno', last: 'C Lázaro' },
      age: 9,
      location: {
        street: { number: 637, name: 'Rua João Gabriel' },
        city: 'Ribeirão Claro',
        state: 'Paraná',
        country: 'Brasil',
        postcode: 86410,
      },
      login: {
        userid: '4',
        username: 'brun1',
        password: 'iug',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Clóvis', last: 'Lázaro Júnior' },
      age: 68,
      location: {
        street: { number: 386, name: 'Rua Marcondes Salgado' },
        city: 'Bernardino de Campos',
        state: 'São Paulo',
        country: 'Brasil',
        postcode: 18960,
      },
      login: {
        userid: '5',
        username: 'clov1',
        password: 'mlsd',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Santina', last: 'Cardoso' },
      age: 70,
      location: {
        street: { number: 35, name: 'Rua do Rosário' },
        city: 'São Pedro do Turvo',
        state: 'São Paulo',
        country: 'Brasil',
        postcode: 18930,
      },
      login: {
        userid: '6',
        username: 'sant1',
        password: 'cvoiw',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Antonio', last: 'Carlos Paschoal' },
      age: 51,
      location: {
        street: { number: 1630, name: 'Rua Minas Gerais' },
        city: 'Rio de Janeiro',
        state: 'Rio de Janeiro',
        country: 'Brasil',
        postcode: 90000,
      },
      login: {
        userid: '7',
        username: 'anto1',
        password: 'rererer',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Ernestina', last: 'Figueiredo' },
      age: 37,
      location: {
        street: { number: 64, name: 'Rua João Miranda' },
        city: 'Manaus',
        state: 'Amazonas',
        country: 'Brasil',
        postcode: 65000,
      },
      login: {
        userid: '8',
        username: 'erne1',
        password: 'jkjhiu',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Pablo', last: 'Escobar' },
      age: 48,
      location: {
        street: { number: 5590, name: 'Rua dos Traficantes' },
        city: 'Poços de Caldas',
        state: 'Minas Gerais',
        country: 'Brasil',
        postcode: 77250,
      },
      login: {
        userid: '9',
        username: 'pabl1',
        password: 'fvioer',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Joana', last: 'Dark' },
      age: 90,
      location: {
        street: { number: 45, name: 'Sítio Maristela' },
        city: 'Goiânia',
        state: 'Goiás',
        country: 'Brasil',
        postcode: 36000,
      },
      login: {
        userid: '10',
        username: 'jan1',
        password: 'vfmoire',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Marília', last: 'Gabriela' },
      age: 28,
      location: {
        street: { number: 1200, name: 'Rua Siqueira Campos' },
        city: 'Brasília',
        state: 'Distrito Federal',
        country: 'Brasil',
        postcode: 10000,
      },
      login: {
        userid: '11',
        username: 'mari1',
        password: 'njfsd',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Cristiano', last: 'J do Amaral' },
      age: 42,
      location: {
        street: { number: 110, name: 'Rua Armando Belleze' },
        city: 'Bernardino de Campos',
        state: 'São Paulo',
        country: 'Brasil',
        postcode: 18960,
      },
      login: {
        userid: '12',
        username: 'crist2',
        password: 'ssdlkj',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Fábio', last: 'Assunçao' },
      age: 33,
      location: {
        street: { number: 23, name: 'Avenida Copacabana' },
        city: 'Rio de Janeiro',
        state: 'Rio de Janeiro',
        country: 'Brasil',
        postcode: 21000,
      },
      login: {
        userid: '13',
        username: 'fabi1',
        password: 'nxvier',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Silvio', last: 'Santos' },
      age: 87,
      location: {
        street: { number: 10, name: 'Rua Jardins' },
        city: 'São Paulo',
        state: 'São Paulo',
        country: 'Brasil',
        postcode: 10100,
      },
      login: {
        userid: '14',
        username: 'silv1',
        password: 'dfsdfds',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Tamy', last: 'Miranda' },
      age: 29,
      location: {
        street: { number: 55, name: 'Avenida Igapó' },
        city: 'Londrina',
        state: 'Paraná',
        country: 'Brasil',
        postcode: 86400,
      },
      login: {
        userid: '15',
        username: 'tam1',
        password: 'sdsdfs',
      },
    },
  ],
};
